---
title: "ESG Rating Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
df <- read_csv('data/SP 500 ESG Risk Ratings.csv')
df_clean <- df[complete.cases(df),]
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
sector_wise_risk <- df_clean %>% group_by(Sector) %>% 
  summarize(mean_ESG_Risk = mean(`Total ESG Risk score`)) %>% 
  arrange(mean_ESG_Risk)
sector_wise_risk %>% ggplot(aes(x = reorder(Sector, mean_ESG_Risk), y=mean_ESG_Risk)) +
  geom_bar(stat = 'identity') + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Sector-wise ESG Risk Analysis",
       x = "Sector",
       y = "Average Total ESG Risk Score")
```

Column {data-width=350 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Environment Risk Score

```{r}
calculate_mean <- function(df, column) {
  df %>%
    group_by(Sector) %>%
    summarize(mean_score = mean(.data[[column]]), .groups = 'drop')
}

risk_columns <- c("Environment Risk Score","Social Risk Score","Governance Risk Score")
mean_ESG <- risk_columns %>% map(~calculate_mean(df_clean,.x))  

names(mean_ESG) <- risk_columns

plot_fun <- function(df) {
  df %>% ggplot(aes(x = reorder(Sector, mean_score), y = mean_score)) +
    geom_bar(stat = 'identity') +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "Sector")
} 
```


```{r}
plot_fun(mean_ESG$`Environment Risk Score`)

```

### Social Risk Score

```{r}
plot_fun(mean_ESG$`Social Risk Score`)
```

### Governance Risk Score

```{r}
plot_fun(mean_ESG$`Governance Risk Score`)
```
